name: HealCommand
version: '1.0.0'
main: winlyps.healCommand.HealCommand
api-version: '1.16'
authors: [ Winlyps ]
commands:
  heal:
    description: Heals the player to their maximum health.
    permission: healcommand.heal
    permission-message: You do not have permission to use this command.